import DashboardSideBar from '@/components/DashboardSideBar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex flex-row w-full h-screen max-h-[92.98vh] container">
            <DashboardSideBar />
            <div className="flex flex-grow py-2 px-5 animate-in">
                {children}
            </div>
        </div>
    )
}
